# Generated by Django 6.0 on 2025-12-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('linkidn', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
            ],
        ),
    ]
