# Generated by Django 6.0 on 2025-12-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_media',
            name='insta',
        ),
        migrations.AddField(
            model_name='social_media',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='social_media',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='linkidn',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
