# Generated by Django 6.0 on 2025-12-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_remove_social_media_insta_social_media_instagram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='social_media',
            new_name='media',
        ),
    ]
